###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: td-assurance-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=td-assurance
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "5002:3306"

    webserver:
      image: nginx:alpine
      container_name: td-assurance-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./html:/usr/share/nginx/html
      ports:
       - "5000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: td-assurance-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

